version: '3.6'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ddev-${DDEV_PROJECT}-phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=db
      - PMA_PASSWORD=db
    ports:
      - "8036:80"
    labels:
      com.ddev.site-url: "phpmyadmin.${DDEV_PROJECT}.ddev.site"
